# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.DateField(verbose_name='Дата покупки')),
                ('reg_numb', models.CharField(editable=False, max_length=6, unique=True, verbose_name='Рег. номер')),
                ('last_refit', models.DateField(blank=True, null=True, verbose_name='Последний осмотр')),
                ('fly_col', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во полётов')),
            ],
            options={
                'verbose_name': 'Самолёт',
                'verbose_name_plural': 'Самолёты',
            },
        ),
        migrations.CreateModel(
            name='PlaneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Модель')),
                ('style', models.PositiveSmallIntegerField(choices=[(1, 'Пассажирский'), (2, 'Чартерный'), (3, 'Почтовый'), (4, 'Военный')], verbose_name='Тип')),
                ('seat', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во мест')),
                ('manufacture', models.DateField(verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Модель самолёта',
                'verbose_name_plural': 'Модели самолётов',
            },
        ),
        migrations.AddField(
            model_name='plane',
            name='plane_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.PlaneType', verbose_name='Модель самолёта'),
        ),
    ]
