# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название Аэропорта')),
                ('sity_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
    ]
