# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, verbose_name='Код рейса')),
                ('airpotr_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_in', to='flight.Airport', verbose_name='Аэропорт влёта')),
                ('airpotr_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_out', to='flight.Airport', verbose_name='Аэропорт вылета')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Plane', verbose_name='Самолёт')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
    ]
