# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='lat',
            field=models.FloatField(default=1, editable=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='lng',
            field=models.FloatField(default=1, editable=False, max_length=30),
            preserve_default=False,
        ),
    ]
