# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='airpotr_in',
            new_name='airport_in',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='airpotr_out',
            new_name='airport_out',
        ),
    ]
